//! The split-sum table: what fraction of an environment a surface sends back.
//!
//! A reflection of a whole environment is an integral over the hemisphere, and
//! the trick every renderer in the field uses is to split it in two: what the
//! environment sends along the reflected direction - which is the prefiltered
//! cube @ref [`env`](crate::env) binds - times what the surface's own lobe does
//! with it, which depends on nothing but two numbers. Two numbers make a table.
//!
//! ```text
//!   reflected = radiance(reflected direction, roughness) * (f0 * A + B)
//!                        ^ the cube                         ^ this table
//! ```
//!
//! **The table is baked here, on the processor, once per device.** The field
//! has four answers to where it comes from - a shipped texture asset, a file in
//! the source tree, a file regenerated by a test, and a compute dispatch at
//! startup - and this is the last of those without the dispatch. The reason is
//! the criterion rather than taste: the term this feeds is held against a
//! numerically integrated split-sum in a test, and that test is only worth
//! running if the shader reads *this* integral rather than a published fit of a
//! different lobe. The fit of that shape everyone quotes is out by six
//! hundredths on average against a real table, and by a fifth at a middling
//! roughness head on, which is a tolerance no test could call a pass.
//!
//! It costs no asset, no format, no file and no pass: [`SIDE`] squared texels
//! of scalar arithmetic, once, before the first frame.
//!
//! **`A` and `B` are this renderer's own lobe, not a copy of one.**
//! [`integrate`] runs the same shadowing term `shader.wgsl` lights with,
//! written out again in double precision, so what the table holds is the
//! integral of the surface the renderer actually draws.

use std::sync::OnceLock;

use colby_core::{Result, err, utils::half::half};
use wgpu::{
	AddressMode, BindGroupLayoutEntry, BindingType, Device, Extent3d, FilterMode, Origin3d,
	Queue, Sampler, SamplerBindingType, SamplerDescriptor, ShaderStages, TexelCopyBufferLayout,
	TexelCopyTextureInfo, TextureAspect, TextureDescriptor, TextureDimension, TextureFormat,
	TextureSampleType, TextureUsages, TextureView, TextureViewDescriptor, TextureViewDimension,
};

/// How many texels the table is on a side.
///
/// Sixty-four, which is what the one engine in the field that ships the table
/// as a file in its own tree ships. Both axes are the same length and neither
/// wants more: the function is smooth in both and the sampler filters between
/// texels. The axes are `n.v` across and roughness down.
pub(crate) const SIDE: u32 = 64;

/// How many samples each texel of the table integrates.
///
/// The same number the environment's own filter uses, for the same reason: one
/// number is one number for a second answer to agree with. @ref
/// `colby_asset::cube::SAMPLES`.
pub(crate) const SAMPLES: u32 = 128;

/// How many bytes one texel takes: four channels of sixteen bits.
const TEXEL_BYTES: u32 = 4;

/// What the table is held in on the device.
///
/// Two channels, because there are two numbers, and half-precision because a
/// two-channel thirty-two-bit format is not filterable without an extension
/// while this one is filterable everywhere. Eight bits a channel would be a
/// quantization of four thousandths, which a sky holding a sun at forty
/// multiplies into several bytes of the picture.
const FORMAT: TextureFormat = TextureFormat::Rg16Float;

/// The table on the device, and the sampler that reads it.
pub(crate) struct Split {
	/// The view the bind group holds, which is the whole of the table.
	///
	/// The texture itself is not held beside it, unlike the environment's:
	/// a view keeps its texture alive, and this one is never rebound, so
	/// there is no second owner to want a say in when the old one goes.
	view: TextureView,

	/// Linear and clamped, which is what reads between two texels.
	sampler: Sampler,
}

impl Split {
	/// Bakes the table and puts it on the device.
	///
	/// @param device - the device to build against
	/// @param queue - the queue the texels are written through
	/// @return the table, or why it could not be built
	pub(crate) fn new(device: &Device, queue: &Queue) -> Result<Self> {
		let bytes = table();
		let wanted = usize::try_from(SIDE * SIDE * TEXEL_BYTES).unwrap_or(0);

		if bytes.len() != wanted {
			return Err(err!(Graphics("the split-sum table came out the wrong size")));
		}

		let texture = device.create_texture(&TextureDescriptor {
			label: Some("split sum"),
			size: Extent3d {
				width: SIDE,
				height: SIDE,
				depth_or_array_layers: 1,
			},
			mip_level_count: 1,
			sample_count: 1,
			dimension: TextureDimension::D2,
			format: FORMAT,
			usage: TextureUsages::TEXTURE_BINDING | TextureUsages::COPY_DST,
			view_formats: &[],
		});

		queue.write_texture(
			TexelCopyTextureInfo {
				texture: &texture,
				mip_level: 0,
				origin: Origin3d::ZERO,
				aspect: TextureAspect::All,
			},
			bytes,
			TexelCopyBufferLayout {
				offset: 0,
				bytes_per_row: Some(SIDE * TEXEL_BYTES),
				rows_per_image: Some(SIDE),
			},
			Extent3d {
				width: SIDE,
				height: SIDE,
				depth_or_array_layers: 1,
			},
		);

		let view = texture.create_view(&TextureViewDescriptor {
			label: Some("split sum"),
			dimension: Some(TextureViewDimension::D2),
			..TextureViewDescriptor::default()
		});

		Ok(Self { view, sampler: sampler(device) })
	}

	/// The view a bind group binds.
	pub(crate) const fn view(&self) -> &TextureView { &self.view }

	/// The sampler it is read through.
	pub(crate) const fn sampler(&self) -> &Sampler { &self.sampler }
}

/// The whole table as the bytes the format wants.
///
/// Row by row, `n.v` across and roughness down. The first texel of a row holds
/// the value at nought and the last the value at one, so the table covers the
/// closed range rather than the middles of sixty-four boxes: the two engines in
/// the field that bake one use the middles and pay for it with a flat half
/// texel at each end, which is exactly where this one is read most - a surface
/// square to the eye, and a roughness of one.
///
/// @ref `shader.wgsl`'s `SPLIT_SIDE`, which is the other half of this: the
/// coordinate a sampler is handed has to be squeezed by the same amount.
///
/// **Baked once for the process.** The table is the same one whatever a world
/// holds, and a scene is built more than once - the editor has one, a test has
/// one each - so the half a million samples behind it are taken the first time
/// somebody asks and handed out after that.
///
/// @return [`SIDE`] squared texels of four half-precision channels, of which
/// the first two are the answer and the other two are what @ref [`FORMAT`]
/// costs
pub(crate) fn table() -> &'static [u8] {
	static BAKED: OnceLock<Vec<u8>> = OnceLock::new();

	BAKED.get_or_init(baked)
}

/// The bake itself, which happens once. @ref [`table`].
#[expect(
	clippy::as_conversions,
	clippy::cast_possible_truncation,
	reason = "an integral worked out in double precision and narrowed once where it is written, \
	          which is the one conversion the arithmetic is for"
)]
fn baked() -> Vec<u8> {
	let mut out = Vec::new();

	for down in 0..SIDE {
		let roughness = place(down);

		for across in 0..SIDE {
			let (scale, bias) = integrate(place(across), roughness);

			out.extend_from_slice(&half(scale as f32).to_le_bytes());
			out.extend_from_slice(&half(bias as f32).to_le_bytes());
		}
	}

	out
}

/// Where along an axis one texel of the table sits, in `0..1`.
///
/// The first is at nought and the last at one. @ref [`table`] for why that and
/// not the middles.
fn place(index: u32) -> f64 { f64::from(index) / f64::from((SIDE - 1).max(1)) }

/// The split-sum integral at one angle and one roughness.
///
/// The surface's reflectance is `f0 * scale + f90 * bias`, and the two come out
/// of one sum: the Fresnel curve is linear in `f0`, so the part that multiplies
/// it and the part that does not can be gathered separately and the caller
/// picks its own colors afterwards. That is the whole reason a table of two
/// numbers can stand in for every material there is.
///
/// The samples are drawn from the distribution itself rather than spread evenly
/// over the hemisphere - the lobe is a spike at a low roughness and a hundred
/// and twenty-eight even samples would miss it entirely - and what each carries
/// is the reflectance with the distribution and the sampling density already
/// divided out against each other.
///
/// @param normal_dot_view - how square the eye is to the surface, in `0..1`
/// @param roughness - the surface's own, in `0..1`
/// @return the part that multiplies `f0` and the part that does not
#[must_use]
pub(crate) fn integrate(normal_dot_view: f64, roughness: f64) -> (f64, f64) {
	let alpha = roughness * roughness;
	let squared = alpha * alpha;
	// the eye, in a frame where the normal is +z and the eye lies in the xz
	// plane: one angle is all the geometry there is, because the lobe is round
	let view = [
		normal_dot_view
			.mul_add(-normal_dot_view, 1.0)
			.max(0.0)
			.sqrt(),
		0.0,
		normal_dot_view,
	];
	let mut scale = 0.0;
	let mut bias = 0.0;

	for index in 0..SAMPLES {
		let (first, second) = hammersley(index, SAMPLES);
		let facet = half_vector(first, second, squared);
		let along = view[0].mul_add(facet[0], view[2] * facet[2]);
		let light = [
			2.0_f64.mul_add(along * facet[0], -view[0]),
			2.0 * along * facet[1],
			2.0_f64.mul_add(along * facet[2], -view[2]),
		];
		let normal_dot_light = light[2];

		if normal_dot_light <= 0.0 {
			continue;
		}

		let normal_dot_half = facet[2].max(1.0e-9);
		let view_dot_half = along.max(0.0);
		// the four is the one the shadowing term has already divided out
		let weight = 4.0
			* visibility(normal_dot_view, normal_dot_light, squared)
			* normal_dot_light
			* view_dot_half
			/ normal_dot_half;
		let curve = (1.0 - view_dot_half).powi(5);

		scale = (1.0 - curve).mul_add(weight, scale);
		bias = curve.mul_add(weight, bias);
	}

	let count = f64::from(SAMPLES.max(1));

	((scale / count).max(0.0), (bias / count).max(0.0))
}

/// How much of the surface shadows itself, already divided by the four times
/// `n.l` times `n.v` the specular term would otherwise need.
///
/// The height-correlated form, which is the one `shader.wgsl` lights with. The
/// table is this renderer's own lobe integrated rather than a published fit of
/// a different one, and this function is where that is decided.
///
/// @param normal_dot_view - how square the eye is to the surface
/// @param normal_dot_light - how square the sample is to it
/// @param squared - the roughness to the fourth
/// @return the shadowing, already divided
fn visibility(normal_dot_view: f64, normal_dot_light: f64, squared: f64) -> f64 {
	let view = normal_dot_light
		* (normal_dot_view * normal_dot_view)
			.mul_add(1.0 - squared, squared)
			.sqrt();
	let light = normal_dot_view
		* (normal_dot_light * normal_dot_light)
			.mul_add(1.0 - squared, squared)
			.sqrt();

	0.5 / (view + light).max(1.0e-12)
}

/// One microfacet normal out of the distribution, for a pair in `0..1`.
///
/// In this frame the normal is +z, so there is no basis to build and no
/// rotation to undo: the whole geometry of the integral is one angle away from
/// straight on. @ref `colby_asset::cube::half_vector`, which is the same
/// inverse with a basis around it.
///
/// @param first - the pair's first coordinate, which turns it around
/// @param second - its second, which tilts it away from the normal
/// @param squared - the roughness to the fourth
/// @return a unit direction
fn half_vector(first: f64, second: f64, squared: f64) -> [f64; 3] {
	let phi = 2.0 * std::f64::consts::PI * first;
	let spread = (squared - 1.0) * second;
	let cosine = ((1.0 - second) / (1.0 + spread).max(1.0e-12))
		.max(0.0)
		.sqrt();
	let sine = (1.0 - cosine * cosine).max(0.0).sqrt();

	[phi.cos() * sine, phi.sin() * sine, cosine]
}

/// The low-discrepancy pair at one place in a sequence of `count`.
///
/// The same sequence the environment's filter draws from and written the same
/// way: the second coordinate is the index's bits reversed, read as a fraction
/// of one. @ref `colby_asset::cube::hammersley`.
///
/// @param index - where in the sequence
/// @param count - how long it is
/// @return the pair, both in `0..1`
fn hammersley(index: u32, count: u32) -> (f64, f64) {
	let first = f64::from(index) / f64::from(count.max(1));

	(first, f64::from(index.reverse_bits()) * 2.328_306_436_538_696_3e-10)
}

/// What the frame's group has to declare for the table and its sampler.
///
/// @param texture - which binding the table takes
/// @param sampler - which binding its sampler takes
/// @return the two entries, in that order
pub(crate) fn layout_entries(texture: u32, sampler: u32) -> [BindGroupLayoutEntry; 2] {
	[
		BindGroupLayoutEntry {
			binding: texture,
			visibility: ShaderStages::FRAGMENT,
			ty: BindingType::Texture {
				sample_type: TextureSampleType::Float { filterable: true },
				view_dimension: TextureViewDimension::D2,
				multisampled: false,
			},
			count: None,
		},
		BindGroupLayoutEntry {
			binding: sampler,
			visibility: ShaderStages::FRAGMENT,
			ty: BindingType::Sampler(SamplerBindingType::Filtering),
			count: None,
		},
	]
}

/// Linear between texels and clamped at both edges.
///
/// Clamped because both axes end where the function does: past a roughness of
/// one and past an eye square to the surface there is nothing to read, and the
/// last texel is the answer. No mip filter, because there is one level.
///
/// @param device - the device to build against
/// @return the sampler
fn sampler(device: &Device) -> Sampler {
	device.create_sampler(&SamplerDescriptor {
		label: Some("split sum"),
		address_mode_u: AddressMode::ClampToEdge,
		address_mode_v: AddressMode::ClampToEdge,
		mag_filter: FilterMode::Linear,
		min_filter: FilterMode::Linear,
		..SamplerDescriptor::default()
	})
}

#[cfg(test)]
mod tests {
	use super::*;

	/// The distribution the samples above are drawn from, written out.
	///
	/// The same function `shader.wgsl` lights with and the same one
	/// [`integrate`] samples by importance - here it is evaluated instead,
	/// because the test below takes the integral the other way round.
	fn distribution(normal_dot_half: f64, squared: f64) -> f64 {
		let divisor = (normal_dot_half * normal_dot_half).mul_add(squared - 1.0, 1.0);

		squared / (std::f64::consts::PI * divisor * divisor)
	}

	/// One even step of [`quadrature`], without the solid angle it covers.
	///
	/// @param view - the eye, in the frame the normal is +z
	/// @param light - the direction this step looks at
	/// @param squared - the roughness to the fourth
	/// @param normal_dot_view - how square the eye is to the surface
	/// @return what this step adds to each of the two sums, per unit of solid
	/// angle
	fn one_step(
		view: [f64; 3],
		light: [f64; 3],
		squared: f64,
		normal_dot_view: f64,
	) -> (f64, f64) {
		let half = [light[0] + view[0], light[1] + view[1], light[2] + view[2]];
		let length = half
			.iter()
			.map(|axis| axis * axis)
			.sum::<f64>()
			.sqrt()
			.max(1.0e-12);
		let normal_dot_half = half[2] / length;
		let view_dot_half = view[2].mul_add(half[2], view[0] * half[0]) / length;

		if normal_dot_half <= 0.0 || view_dot_half <= 0.0 {
			return (0.0, 0.0);
		}

		// the cosine the reflected light is weighted by, times the specular
		// term with no Fresnel in it
		let term = distribution(normal_dot_half, squared)
			* visibility(normal_dot_view, light[2], squared)
			* light[2];
		let curve = (1.0 - view_dot_half).powi(5);

		((1.0 - curve) * term, curve * term)
	}

	/// The same integral by even steps over the hemisphere rather than by
	/// drawing from the lobe.
	///
	/// A different estimator of the same number: this one evaluates the
	/// distribution and divides by nothing, where [`integrate`] samples the
	/// distribution and lets it cancel. Two ways of being wrong that do not
	/// overlap.
	///
	/// @param normal_dot_view - how square the eye is to the surface
	/// @param roughness - the surface's own
	/// @param steps - how many along each of the two angles
	/// @return the part that multiplies `f0` and the part that does not
	fn quadrature(normal_dot_view: f64, roughness: f64, steps: u32) -> (f64, f64) {
		let squared = (roughness * roughness).powi(2);
		let view = [
			normal_dot_view
				.mul_add(-normal_dot_view, 1.0)
				.max(0.0)
				.sqrt(),
			0.0,
			normal_dot_view,
		];
		let count = f64::from(steps);
		let mut scale = 0.0;
		let mut bias = 0.0;

		// the solid angle one step covers, which is the same for every one of
		// them because the steps are even in the cosine
		let solid = 2.0 * std::f64::consts::PI / (count * count);

		for down in 0..steps {
			let cosine = (f64::from(down) + 0.5) / count;
			let sine = (1.0 - cosine * cosine).max(0.0).sqrt();

			for around in 0..steps {
				let turn = 2.0 * std::f64::consts::PI * (f64::from(around) + 0.5) / count;
				let light = [turn.cos() * sine, turn.sin() * sine, cosine];
				let (step_scale, step_bias) = one_step(view, light, squared, normal_dot_view);

				scale = step_scale.mul_add(solid, scale);
				bias = step_bias.mul_add(solid, bias);
			}
		}

		(scale, bias)
	}

	#[test]
	fn the_table_agrees_with_the_same_integral_taken_the_other_way_round() {
		// two estimators of one number, and neither is the other written
		// twice: one draws its samples from the lobe and lets the distribution
		// cancel, the other walks the hemisphere in even steps and evaluates
		// it. A hundred and twenty-eight drawn samples are worth about as much
		// as a million even ones, and the worst of the six below is five parts
		// in a thousand apart.
		//
		// **Only from a middling roughness up**, and that is the method's
		// limit rather than the table's: at a roughness of 0.1 the lobe is a
		// spike a few degrees wide and a step of a thousandth in the cosine
		// walks straight over it - even steps answer 0.37 where the truth is
		// 1.0. Where the lobe is a spike, drawing from it is the only way.
		for roughness in [0.5_f64, 0.7, 1.0] {
			for view in [1.0_f64, 0.6] {
				let (scale, bias) = integrate(view, roughness);
				let (other_scale, other_bias) = quadrature(view, roughness, 1024);
				let whole = scale + bias;
				let other = other_scale + other_bias;

				assert!(
					(whole - other).abs() < 0.008,
					"at n.v {view} and a roughness of {roughness} the drawn samples say {whole} \
					 and the even ones {other}"
				);
			}
		}
	}

	#[test]
	fn at_the_one_place_the_integral_has_a_closed_form_both_estimators_land_on_it() {
		// with the roughness at one and the eye square to the surface the
		// integral collapses: the distribution is flat, so the sample's own
		// cosine is even in its square, the shadowing term is `1/(n.l + 1)`,
		// and what is left integrates to `1 - ln 2` exactly. It is the only
		// point on the table with an answer that owes nothing to arithmetic
		let exact = 1.0 - std::f64::consts::LN_2;
		let (scale, bias) = quadrature(1.0, 1.0, 1024);
		let (drawn_scale, drawn_bias) = integrate(1.0, 1.0);

		assert!(
			(scale + bias - exact).abs() < 1.0e-4,
			"even steps say {} where the arithmetic says {exact}",
			scale + bias
		);
		assert!(
			(drawn_scale + drawn_bias - exact).abs() < 0.005,
			"and a hundred and twenty-eight drawn samples say {}",
			drawn_scale + drawn_bias
		);
	}

	#[test]
	fn a_smooth_surface_sends_back_everything_and_a_rough_one_loses_by_itself() {
		// the single bounce the table holds keeps all of a smooth surface's
		// light and two thirds of a chalk one's, which is the whole reason the
		// shader multiplies what comes out of it by a compensation
		for view in [1.0_f64, 0.7, 0.4] {
			let (scale, bias) = integrate(view, 0.02);

			assert!(
				(scale + bias - 1.0).abs() < 0.01,
				"a mirror at n.v {view} keeps {}",
				scale + bias
			);
		}

		let (scale, bias) = integrate(1.0, 1.0);
		let whole = scale + bias;

		assert!(
			(0.25..0.35).contains(&whole),
			"and chalk head on keeps {whole}, where a single bounce keeps about three tenths"
		);
	}

	#[test]
	fn the_reflectance_never_climbs_past_what_arrives() {
		// the compensation is a multiplication by a number well above one, and
		// what stops it inventing light is an identity rather than a clamp:
		// `(f0 A + B) / (A + B)` is at most one when `f0` is
		let places = [0.05_f64, 0.3, 0.6, 1.0]
			.into_iter()
			.flat_map(|roughness| [1.0_f64, 0.6, 0.2, 0.02].map(|view| (roughness, view)));

		for (roughness, view) in places {
			let (scale, bias) = integrate(view, roughness);
			let kept = (scale + bias).max(1.0e-4);

			for f0 in [0.04_f64, 0.5, 1.0] {
				let whole = f0.mul_add(scale, bias) * f0.mul_add(1.0 / kept - 1.0, 1.0);

				assert!(
					whole <= 1.0 + 1.0e-9,
					"at n.v {view}, f0 {f0} and a roughness of {roughness} a surface sends back \
					 {whole} of what reaches it"
				);
			}
		}
	}

	#[test]
	fn the_table_is_the_shape_the_format_wants_and_its_corners_are_the_integral() {
		let bytes = table();
		let wanted = usize::try_from(SIDE * SIDE * TEXEL_BYTES).expect("a table of a few dozen");

		assert_eq!(bytes.len(), wanted, "two channels of two bytes, {SIDE} squared");

		// the first texel of a row is the value at nought and the last the
		// value at one: the corner of the table nearest the eye is a mirror
		// seen head on, which sends everything back
		let last = usize::try_from(SIDE - 1).expect("a table of a few dozen");
		let corner = read(bytes, last, 0);

		assert!(
			(corner.0 + corner.1 - 1.0).abs() < 0.01,
			"a mirror head on keeps {} of what reaches it",
			corner.0 + corner.1
		);

		let chalk = read(bytes, last, last);
		let (scale, bias) = integrate(1.0, 1.0);

		assert!(
			(f64::from(chalk.0) - scale).abs() < 1.0e-3
				&& (f64::from(chalk.1) - bias).abs() < 1.0e-3,
			"and the far corner is the integral at a roughness of one: {chalk:?} against \
			 {scale} and {bias}"
		);
	}

	/// One texel of the table read back out of its bytes.
	///
	/// @param bytes - the whole table
	/// @param across - which column, along `n.v`
	/// @param down - which row, along the roughness
	/// @return the two numbers there
	fn read(bytes: &[u8], across: usize, down: usize) -> (f32, f32) {
		let side = usize::try_from(SIDE).expect("a table of a few dozen");
		let stride = usize::try_from(TEXEL_BYTES).expect("a texel of a few bytes");
		let at = (down * side + across) * stride;
		let pair = |from: usize| {
			let low = bytes.get(from).copied().unwrap_or(0);
			let high = bytes.get(from + 1).copied().unwrap_or(0);

			widened(u16::from_le_bytes([low, high]))
		};

		(pair(at), pair(at + 2))
	}

	/// One of the format's sixteen-bit values back as a number.
	///
	/// Written out rather than taken from a crate, for the reason the same
	/// function in `colby_asset::cube`'s tests is.
	fn widened(bits: u16) -> f32 {
		let exponent = i32::from((bits >> 10) & 0x1F);
		let mantissa = f32::from(bits & 0x03FF);

		if exponent == 0 {
			return mantissa * 2.0_f32.powi(-24);
		}

		(1.0 + mantissa / 1024.0) * 2.0_f32.powi(exponent - 15)
	}
}
